# golangci-lint configuration for terraform-provider-rediscloud
# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 10m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - govet         # Report suspicious constructs
    - staticcheck   # Static analysis

    # Additional recommended linters
    - bodyclose     # Check HTTP response body is closed
    - durationcheck # Check for duration multiplication issues
    - errorlint     # Find code that will cause problems with Go 1.13 error wrapping
    - misspell      # Find commonly misspelled English words
    - nilerr        # Find code that returns nil even if error is not nil
    - noctx         # Find HTTP requests without context.Context
    - prealloc      # Find slice declarations that could be preallocated
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters
    - wastedassign  # Find wasted assignment statements

  settings:
    errcheck:
      # Report about not checking errors in type assertions: `a := b.(MyStruct)`
      check-type-assertions: true

    govet:
      # Enable all analyzers
      enable-all: true
      disable:
        - fieldalignment  # Too noisy for existing codebase

    misspell:
      locale: UK

    staticcheck:
      # Enable all checks
      checks: ["all"]

  exclusions:
    # Maximum count of issues with the same text (0 = unlimited)
    max-same-issues: 0

    rules:
      # Ignore some checks in test files
      - path: _test\.go
        linters:
          - unparam  # Test functions often have unused parameters for consistency

      - path: _test\.go
        text: "fieldalignment:"

formatters:
  enable:
    - gofmt         # Check code is formatted
    - goimports     # Check imports are organised

  settings:
    goimports:
      # Put local imports after 3rd-party packages
      local-prefixes:
        - github.com/RedisLabs/terraform-provider-rediscloud
