name: Terraform Provider Checks - main branch

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup-nix
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix develop --command make ci

  testacc-databases:
    name: Acceptance Tests (Databases)
    needs: [ci]
    uses: ./.github/workflows/testacc.yml
    with:
      test_pattern: TestAcc(DataSource|Resource)RedisCloud(Essentials|Pro|ActiveActive)Database_.*
    secrets: inherit

  testacc-subscriptions:
    name: Acceptance Tests (Subscriptions)
    needs: [ci]
    uses: ./.github/workflows/testacc.yml
    with:
      test_pattern: TestAcc(DataSource|Resource)RedisCloud(Essentials|Pro|ActiveActive)Subscription_.*
    secrets: inherit

  testacc-subscriptions-tls:
    name: Acceptance Tests (Subscriptions TLS)
    needs: [ci]
    uses: ./.github/workflows/testacc.yml
    with:
      test_pattern: TestAcc(DataSource|Resource)RedisCloudSubscriptionTls_.*
    secrets: inherit

  testacc-essentials-plan:
    name: Acceptance Tests (Essentials Plan)
    needs: [ci]
    uses: ./.github/workflows/testacc.yml
    with:
      test_pattern: TestAcc(DataSource|Resource)RedisCloudEssentialsPlan_.*
    secrets: inherit

  testacc-persistence-modules-regions-acl:
    name: Acceptance Tests (Persistence Modules Regions ACL)
    needs: [ci]
    uses: ./.github/workflows/testacc.yml
    with:
      test_pattern: TestAcc(DataSource|Resource)RedisCloud(DataPersistence|DatabaseModules|Regions|Acl).*
    secrets: inherit

  testacc-cloud-account:
    name: Acceptance Tests (Cloud Account)
    needs: [ci]
    uses: ./.github/workflows/testacc.yml
    with:
      test_pattern: TestAcc(DataSource|Resource)RedisCloud(CloudAccount).*
    secrets: inherit

  testacc-transit-payment:
    name: Acceptance Tests (Transit Payment)
    needs: [ci]
    uses: ./.github/workflows/testacc.yml
    with:
      test_pattern: TestAcc(DataSource|Resource)RedisCloud(TransitGatewayAttachment|PaymentMethod).*
    secrets: inherit
